/**
 * Copyright 2026 Jake Butler
 * @license Apache-2.0, see LICENSE for full text.
 *
 * Vercel serverless function - Route: /api/posts
 * Returns Invincible photo gallery data
 */
export default function handler(req, res) {
  const data = {
    authors: [
      {
        authorID: 1,
        username: "markgrayson17",
        profileImg: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg",
        userSince: "2026",
        channel: "Invincible Official",
      },
    ],
    posts: [
      {
        postID: 1,
        authorID: 1,
        title: "Almost Killed Cecil",
        dateTaken: "2026-01-01",
        thumbnail: "https://4kwallpapers.com/images/wallpapers/invincible-season-3-2048x2048-20175.png",
        image: "https://4kwallpapers.com/images/wallpapers/invincible-season-3-2048x2048-20175.png",
        caption: "This was like the fourth time I almost killed Cecil.",
        alt: "Invincible standing over Cecil in a tense confrontation",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 2,
        authorID: 1,
        title: "Aura Farming",
        dateTaken: "2026-01-02",
        thumbnail: "https://images.alphacoders.com/114/1140274.jpg",
        image: "https://images.alphacoders.com/114/1140274.jpg",
        caption: "Chicago was obliterated but im aura farming.",
        alt: "Invincible posing heroically with a destroyed city behind him",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 3,
        authorID: 1,
        title: "Before Reanimen",
        dateTaken: "2026-01-03",
        thumbnail: "https://c4.wallpaperflare.com/wallpaper/728/77/205/invincible-mark-grayson-invincible-superhero-hd-wallpaper-preview.jpg",
        image: "https://c4.wallpaperflare.com/wallpaper/728/77/205/invincible-mark-grayson-invincible-superhero-hd-wallpaper-preview.jpg",
        caption: "Me before I destroy reanimen.",
        alt: "Invincible ready for battle in his blue and yellow suit",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 4,
        authorID: 1,
        title: "Invincible War",
        dateTaken: "2026-01-04",
        thumbnail: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2025/03/invincible-season-3-mark-multiverse.jpg?w=1200&h=900&fit=crop",
        image: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2025/03/invincible-season-3-mark-multiverse.jpg?w=1200&h=900&fit=crop",
        caption: "The start of the invincible war #notcoolbro",
        alt: "Multiple versions of Invincible facing off during the Invincible War",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 5,
        authorID: 1,
        title: "Beautiful Day",
        dateTaken: "2026-01-05",
        thumbnail: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg",
        image: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg",
        caption: "Smilin on a beautiful day",
        alt: "Mark Grayson smiling in his Invincible costume",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 6,
        authorID: 1,
        title: "Handsome and Wealthy",
        dateTaken: "2026-01-06",
        thumbnail: "https://i.pinimg.com/736x/26/9b/05/269b052619e530b5d7f2cfe193c4fdf7.jpg",
        image: "https://i.pinimg.com/736x/26/9b/05/269b052619e530b5d7f2cfe193c4fdf7.jpg",
        caption: "Handsome and Wealthy - Migos.",
        alt: "Invincible looking confident in full costume",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 7,
        authorID: 1,
        title: "Who I Saw In Space",
        dateTaken: "2026-01-07",
        thumbnail: "https://www.dexerto.com/cdn-image/wp-content/uploads/2026/04/02/Does-Mark-survive-Invincible-vs-Conquest-2-Comics-reveal-fate-after-S4E5-explained.jpg?width=1200&quality=75&format=auto",
        image: "https://www.dexerto.com/cdn-image/wp-content/uploads/2026/04/02/Does-Mark-survive-Invincible-vs-Conquest-2-Comics-reveal-fate-after-S4E5-explained.jpg?width=1200&quality=75&format=auto",
        caption: "Cecil you would not believe who I saw in space...",
        alt: "Invincible and Conquest facing off in an intense battle",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 8,
        authorID: 1,
        title: "For My Mom",
        dateTaken: "2026-01-08",
        thumbnail: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1200,ar_1:1,f_auto,q_auto,g_auto/images/ImageExchange/mmsport/385/01jec3s056171qbvv6d6.jpg",
        image: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1200,ar_1:1,f_auto,q_auto,g_auto/images/ImageExchange/mmsport/385/01jec3s056171qbvv6d6.jpg",
        caption: "Took these for my mom.",
        alt: "Invincible mid-flight over the city",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 9,
        authorID: 1,
        title: "Saving Dad",
        dateTaken: "2026-01-09",
        thumbnail: "https://i.ytimg.com/vi/yYvkXGgTdfE/sddefault.jpg",
        image: "https://i.ytimg.com/vi/yYvkXGgTdfE/sddefault.jpg",
        caption: "Conquest about to squeeze my dads head off until I stepped in.",
        alt: "Conquest grabbing Omni-Man while Invincible intervenes",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 10,
        authorID: 1,
        title: "Worst Day Ever",
        dateTaken: "2026-01-10",
        thumbnail: "https://i.redd.it/y8crj0fz6sfb1.jpg",
        image: "https://i.redd.it/y8crj0fz6sfb1.jpg",
        caption: "#worstdayever",
        alt: "Invincible beaten and battered after a brutal fight",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 11,
        authorID: 1,
        title: "Dad Is Back",
        dateTaken: "2026-01-11",
        thumbnail: "https://www.absolutegeeks.com/wp-content/uploads/2026/04/first-clip-from-s4-episode-5-v0-dzg0ZHByZDVlN3NnMdoNIpYArfRzKYHAiyXKBCv70J-_LyK0MPAzUDgTLICN.png.webp",
        image: "https://www.absolutegeeks.com/wp-content/uploads/2026/04/first-clip-from-s4-episode-5-v0-dzg0ZHByZDVlN3NnMdoNIpYArfRzKYHAiyXKBCv70J-_LyK0MPAzUDgTLICN.png.webp",
        caption: "My dad just showed back up with seth rogan.",
        alt: "Omni-Man returning alongside a familiar face",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 12,
        authorID: 1,
        title: "Monday Workout",
        dateTaken: "2026-01-12",
        thumbnail: "https://preview.redd.it/how-big-of-a-role-do-yall-think-cecils-training-played-in-v0-h0qmpr9g8koe1.jpeg?width=640&crop=smart&auto=webp&s=a2a490587a631246c5412e66b964835fe9d9d230",
        image: "https://preview.redd.it/how-big-of-a-role-do-yall-think-cecils-training-played-in-v0-h0qmpr9g8koe1.jpeg?width=640&crop=smart&auto=webp&s=a2a490587a631246c5412e66b964835fe9d9d230",
        caption: "Benching the weight of the moon on a monday",
        alt: "Invincible training and lifting an enormous amount of weight",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 13,
        authorID: 1,
        title: "Still Have You Dad",
        dateTaken: "2026-01-13",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6mahPXG8DzTq2wOcvMwxUa68QYkSTnjVUqA&s",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6mahPXG8DzTq2wOcvMwxUa68QYkSTnjVUqA&s",
        caption: "I'd still have you, dad.",
        alt: "Mark Grayson and Omni-Man sharing a quiet moment together",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 14,
        authorID: 1,
        title: "Tearing Up Flaxus",
        dateTaken: "2026-01-14",
        thumbnail: "https://i.ytimg.com/vi/1v9C45OP_8w/maxresdefault.jpg",
        image: "https://i.ytimg.com/vi/1v9C45OP_8w/maxresdefault.jpg",
        caption: "My dad tearing up flaxus.",
        alt: "Omni-Man unleashing his full power on the planet Flaxus",
        views: "256 views",
        likes: 31,
      },
      {
        postID: 15,
        authorID: 1,
        title: "Bailing Out Oliver",
        dateTaken: "2026-01-15",
        thumbnail: "https://preview.redd.it/this-conquest-frame-hits-different-v0-knxbu1c0ijsg1.png?width=640&crop=smart&auto=webp&s=13f31bff692d3d96a6a22df571a2b2d54fd0bf51",
        image: "https://preview.redd.it/this-conquest-frame-hits-different-v0-knxbu1c0ijsg1.png?width=640&crop=smart&auto=webp&s=13f31bff692d3d96a6a22df571a2b2d54fd0bf51",
        caption: "Oliver before I bailed him out for the 20th time",
        alt: "Invincible rescuing his younger brother Oliver from a dangerous situation",
        views: "256 views",
        likes: 31,
      },
    ],
  };

  res.setHeader("Content-Type", "application/json");
  res.status(200).json(data);
}