/**
 * Copyright 2026 Jake Butler
 * @license Apache-2.0, see LICENSE for full text.
 *
 * Vercel serverless function
 * Route: /api/instagram-data
 */
export default function handler(request, res) {
  const data = {
    title: "InvincibleGram",
    author: {
      name: "Mark Grayson",
      handle: "markgrayson17",
      image: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg",
      userSince: "2026",
      channel: "Invincible Official",
    },
    images: [
      { id: "inv-1", title: "Almost Killed Cecil", description: "This was like the fourth time I almost killed Cecil.", alt: "Invincible standing over Cecil in a tense confrontation", image: "https://4kwallpapers.com/images/wallpapers/invincible-season-3-2048x2048-20175.png", thumbnail: "https://4kwallpapers.com/images/wallpapers/invincible-season-3-2048x2048-20175.png", full: "https://4kwallpapers.com/images/wallpapers/invincible-season-3-2048x2048-20175.png", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-01", views: "256 views", likes: 31 },
      { id: "inv-2", title: "Aura Farming", description: "Chicago was obliterated but im aura farming.", alt: "Invincible posing heroically with a destroyed city behind him", image: "https://images.alphacoders.com/114/1140274.jpg", thumbnail: "https://images.alphacoders.com/114/1140274.jpg", full: "https://images.alphacoders.com/114/1140274.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-02", views: "256 views", likes: 31 },
      { id: "inv-3", title: "Before Reanimen", description: "Me before I destroy reanimen.", alt: "Invincible ready for battle in his blue and yellow suit", image: "https://c4.wallpaperflare.com/wallpaper/728/77/205/invincible-mark-grayson-invincible-superhero-hd-wallpaper-preview.jpg", thumbnail: "https://c4.wallpaperflare.com/wallpaper/728/77/205/invincible-mark-grayson-invincible-superhero-hd-wallpaper-preview.jpg", full: "https://c4.wallpaperflare.com/wallpaper/728/77/205/invincible-mark-grayson-invincible-superhero-hd-wallpaper-preview.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-03", views: "256 views", likes: 31 },
      { id: "inv-4", title: "Invincible War", description: "The start of the invincible war.", alt: "Multiple versions of Invincible facing off during the Invincible War", image: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2025/03/invincible-season-3-mark-multiverse.jpg?w=1200&h=900&fit=crop", thumbnail: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2025/03/invincible-season-3-mark-multiverse.jpg?w=1200&h=900&fit=crop", full: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2025/03/invincible-season-3-mark-multiverse.jpg?w=1200&h=900&fit=crop", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-04", views: "256 views", likes: 31 },
      { id: "inv-5", title: "Beautiful Day", description: "Smiling on a beautiful day.", alt: "Mark Grayson smiling in his Invincible costume", image: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg", thumbnail: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg", full: "https://i.pinimg.com/736x/82/f1/63/82f163dcb5de22326d3c89a9b1b4b772.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-05", views: "256 views", likes: 31 },
      { id: "inv-6", title: "Handsome and Wealthy", description: "Handsome and wealthy.", alt: "Invincible looking confident in full costume", image: "https://i.pinimg.com/736x/26/9b/05/269b052619e530b5d7f2cfe193c4fdf7.jpg", thumbnail: "https://i.pinimg.com/736x/26/9b/05/269b052619e530b5d7f2cfe193c4fdf7.jpg", full: "https://i.pinimg.com/736x/26/9b/05/269b052619e530b5d7f2cfe193c4fdf7.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-06", views: "256 views", likes: 31 },
      { id: "inv-7", title: "Who I Saw In Space", description: "Cecil, you would not believe who I saw in space.", alt: "Invincible and Conquest facing off in an intense battle", image: "https://www.dexerto.com/cdn-image/wp-content/uploads/2026/04/02/Does-Mark-survive-Invincible-vs-Conquest-2-Comics-reveal-fate-after-S4E5-explained.jpg?width=1200&quality=75&format=auto", thumbnail: "https://www.dexerto.com/cdn-image/wp-content/uploads/2026/04/02/Does-Mark-survive-Invincible-vs-Conquest-2-Comics-reveal-fate-after-S4E5-explained.jpg?width=1200&quality=75&format=auto", full: "https://www.dexerto.com/cdn-image/wp-content/uploads/2026/04/02/Does-Mark-survive-Invincible-vs-Conquest-2-Comics-reveal-fate-after-S4E5-explained.jpg?width=1200&quality=75&format=auto", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-07", views: "256 views", likes: 31 },
      { id: "inv-8", title: "For My Mom", description: "Took these for my mom.", alt: "Invincible mid-flight over the city", image: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1200,ar_1:1,f_auto,q_auto,g_auto/images/ImageExchange/mmsport/385/01jec3s056171qbvv6d6.jpg", thumbnail: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1200,ar_1:1,f_auto,q_auto,g_auto/images/ImageExchange/mmsport/385/01jec3s056171qbvv6d6.jpg", full: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1200,ar_1:1,f_auto,q_auto,g_auto/images/ImageExchange/mmsport/385/01jec3s056171qbvv6d6.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-08", views: "256 views", likes: 31 },
      { id: "inv-9", title: "Saving Dad", description: "Conquest almost got my dad until I stepped in.", alt: "Conquest grabbing Omni-Man while Invincible intervenes", image: "https://i.ytimg.com/vi/yYvkXGgTdfE/sddefault.jpg", thumbnail: "https://i.ytimg.com/vi/yYvkXGgTdfE/sddefault.jpg", full: "https://i.ytimg.com/vi/yYvkXGgTdfE/sddefault.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-09", views: "256 views", likes: 31 },
      { id: "inv-10", title: "Worst Day Ever", description: "Worst day ever.", alt: "Invincible beaten and battered after a brutal fight", image: "https://i.redd.it/y8crj0fz6sfb1.jpg", thumbnail: "https://i.redd.it/y8crj0fz6sfb1.jpg", full: "https://i.redd.it/y8crj0fz6sfb1.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-10", views: "256 views", likes: 31 },
      { id: "inv-11", title: "Dad Is Back", description: "My dad just showed back up.", alt: "Omni-Man returning alongside a familiar face", image: "https://www.absolutegeeks.com/wp-content/uploads/2026/04/first-clip-from-s4-episode-5-v0-dzg0ZHByZDVlN3NnMdoNIpYArfRzKYHAiyXKBCv70J-_LyK0MPAzUDgTLICN.png.webp", thumbnail: "https://www.absolutegeeks.com/wp-content/uploads/2026/04/first-clip-from-s4-episode-5-v0-dzg0ZHByZDVlN3NnMdoNIpYArfRzKYHAiyXKBCv70J-_LyK0MPAzUDgTLICN.png.webp", full: "https://www.absolutegeeks.com/wp-content/uploads/2026/04/first-clip-from-s4-episode-5-v0-dzg0ZHByZDVlN3NnMdoNIpYArfRzKYHAiyXKBCv70J-_LyK0MPAzUDgTLICN.png.webp", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-11", views: "256 views", likes: 31 },
      { id: "inv-12", title: "Monday Workout", description: "Training hard on a Monday.", alt: "Invincible training and lifting an enormous amount of weight", image: "https://preview.redd.it/how-big-of-a-role-do-yall-think-cecils-training-played-in-v0-h0qmpr9g8koe1.jpeg?width=640&crop=smart&auto=webp&s=a2a490587a631246c5412e66b964835fe9d9d230", thumbnail: "https://preview.redd.it/how-big-of-a-role-do-yall-think-cecils-training-played-in-v0-h0qmpr9g8koe1.jpeg?width=640&crop=smart&auto=webp&s=a2a490587a631246c5412e66b964835fe9d9d230", full: "https://preview.redd.it/how-big-of-a-role-do-yall-think-cecils-training-played-in-v0-h0qmpr9g8koe1.jpeg?width=640&crop=smart&auto=webp&s=a2a490587a631246c5412e66b964835fe9d9d230", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-12", views: "256 views", likes: 31 },
      { id: "inv-13", title: "Still Have You Dad", description: "I would still have you, dad.", alt: "Mark Grayson and Omni-Man sharing a quiet moment together", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6mahPXG8DzTq2wOcvMwxUa68QYkSTnjVUqA&s", thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6mahPXG8DzTq2wOcvMwxUa68QYkSTnjVUqA&s", full: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6mahPXG8DzTq2wOcvMwxUa68QYkSTnjVUqA&s", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-13", views: "256 views", likes: 31 },
      { id: "inv-14", title: "Tearing Up Flaxus", description: "My dad tearing up Flaxus.", alt: "Omni-Man unleashing his full power on the planet Flaxus", image: "https://i.ytimg.com/vi/1v9C45OP_8w/maxresdefault.jpg", thumbnail: "https://i.ytimg.com/vi/1v9C45OP_8w/maxresdefault.jpg", full: "https://i.ytimg.com/vi/1v9C45OP_8w/maxresdefault.jpg", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-14", views: "256 views", likes: 31 },
      { id: "inv-15", title: "Bailing Out Oliver", description: "Oliver before I bailed him out again.", alt: "Invincible rescuing his younger brother Oliver from a dangerous situation", image: "https://preview.redd.it/this-conquest-frame-hits-different-v0-knxbu1c0ijsg1.png?width=640&crop=smart&auto=webp&s=13f31bff692d3d96a6a22df571a2b2d54fd0bf51", thumbnail: "https://preview.redd.it/this-conquest-frame-hits-different-v0-knxbu1c0ijsg1.png?width=640&crop=smart&auto=webp&s=13f31bff692d3d96a6a22df571a2b2d54fd0bf51", full: "https://preview.redd.it/this-conquest-frame-hits-different-v0-knxbu1c0ijsg1.png?width=640&crop=smart&auto=webp&s=13f31bff692d3d96a6a22df571a2b2d54fd0bf51", source: "https://www.amazon.com/invincible", dateTaken: "2026-01-15", views: "256 views", likes: 31 },
    ],
  };

  res.setHeader("Cache-Control", "max-age=0, s-maxage=86400");
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,PATCH,DELETE,POST,PUT");
  res.setHeader("Access-Control-Allow-Headers", "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version");
  res.json(data);
}